Auto <- read.csv("Auto.csv", header = TRUE, na.strings = "?")
mean(Auto$mpg)
mean(Auto$mpg[Auto$cylinders == 4])
mean(Auto$mpg[Auto$year == 72])
var(Auto$acceleration)
var(Auto$acceleration[Auto$origin == 3])
length(na.omit(Auto$horsepower[Auto$horsepower > mean(na.omit(Auto$horsepower))]))
max(na.omit(Auto$horsepower[Auto$weight < mean(Auto$weight)]))
length(Auto$mpg[Auto$mpg > mean(Auto$mpg)])
min(Auto$cylinders[Auto$mpg < mean(Auto$mpg)])
length(Auto$mpg[Auto$displacement == max(Auto$displacement)])
max(Auto$weight[Auto$displacement < median(Auto$displacement)])
